# Generated by Django 2.0.2 on 2018-02-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away', models.CharField(max_length=50)),
                ('a_score', models.IntegerField(default=0)),
                ('home', models.CharField(max_length=50)),
                ('h_score', models.IntegerField(default=0)),
                ('league', models.CharField(choices=[('OHL', 'Ontario Hockey League'), ('QMJHL', 'Quebec Major Junior Hockey League'), ('WHL', 'Western Hockey League')], max_length=5)),
                ('resultado', models.CharField(choices=[('', ''), ('f', 'FINAL'), ('ot', 'FINAL-OT'), ('so', 'FINAL-SO')], default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abr', models.CharField(max_length=5)),
                ('league', models.CharField(choices=[('OHL', 'Ontario Hockey League'), ('QMJHL', 'Quebec Major Junior Hockey League'), ('WHL', 'Western Hockey League')], max_length=5)),
                ('pts', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('otl', models.IntegerField(default=0)),
                ('sol', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('streak', models.CharField(default='W0', max_length=3)),
            ],
        ),
    ]
