# Generated by Django 2.0.2 on 2018-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
