# Generated by Django 2.0.2 on 2018-03-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0002_auto_20180223_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='POseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high', models.CharField(default='', max_length=100)),
                ('h_msg', models.CharField(max_length=100)),
                ('h_wins', models.IntegerField(default=0)),
                ('low', models.CharField(default='', max_length=100)),
                ('l_wins', models.IntegerField(default=0)),
                ('series', models.CharField(max_length=150)),
                ('league', models.CharField(choices=[('OHL', 'Ontario Hockey League'), ('QMJHL', 'Quebec Major Junior Hockey League'), ('WHL', 'Western Hockey League')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
