# Generated by Django 2.0.2 on 2018-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0003_auto_20180304_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='poseries',
            name='l_msg',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='poseries',
            name='h_msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
