# Generated by Django 2.0.2 on 2018-03-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0004_auto_20180304_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='poseries',
            name='conference',
            field=models.CharField(default='', max_length=30),
        ),
    ]
