# Generated by Django 2.0.2 on 2018-03-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0005_poseries_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='h_leagues.POseries'),
        ),
    ]
