# Generated by Django 2.0.2 on 2018-03-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0006_match_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='series',
        ),
    ]
