# Generated by Django 2.0.2 on 2018-04-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0008_auto_20180403_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('wild_card', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30)),
                ('tops', models.IntegerField(default=1)),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('name', models.CharField(choices=[('OHL', 'Ontario Hockey League'), ('QMJHL', 'Quebec Major Junior Hockey League'), ('WHL', 'Western Hockey League')], max_length=5, primary_key=True, serialize=False)),
                ('n_games', models.IntegerField(default=1)),
                ('weeks', models.IntegerField(default=1)),
                ('color', models.CharField(default='', max_length=10)),
                ('bg_color', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('home_adv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PostSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('end_point', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PSMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField(default=1)),
                ('h_score', models.IntegerField(default=0)),
                ('a_score', models.IntegerField(default=0)),
                ('result', models.CharField(default='', max_length=15)),
                ('storyline', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RS_clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=1)),
                ('po_marks', models.IntegerField(choices=[(1, 'x - '), (2, 'y - '), (3, 'z - '), (0, '')], default=0)),
                ('pts', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('otl', models.IntegerField(default=0)),
                ('sol', models.IntegerField(default=0)),
                ('gf', models.IntegerField(default=0)),
                ('ga', models.IntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('last5', models.CharField(default=' - - - - ', max_length=15)),
                ('streak', models.CharField(default='W 0', max_length=3)),
                ('div_placement', models.IntegerField(default=1)),
                ('off_power', models.IntegerField(default=500)),
                ('momentum', models.IntegerField(default=500)),
                ('def_power', models.IntegerField(default=500)),
                ('l_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.League')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('start', models.IntegerField()),
                ('final', models.IntegerField(primary_key=True, serialize=False)),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('identifier', models.CharField(default='', max_length=2)),
                ('conf', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=20)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.League')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_champ', models.BooleanField(default=False)),
                ('division', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='POseries',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='resultado',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='team',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ga',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gf',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='team',
            name='otl',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pts',
        ),
        migrations.RemoveField(
            model_name='team',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sol',
        ),
        migrations.RemoveField(
            model_name='team',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AddField(
            model_name='match',
            name='a_rec',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='match',
            name='h_rec',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='team',
            name='bg_color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='h_leagues.RS_clubs'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='h_leagues.RS_clubs'),
        ),
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='abr',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Division'),
        ),
        migrations.AddField(
            model_name='winners',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Team'),
        ),
        migrations.AddField(
            model_name='winners',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.League'),
        ),
        migrations.AddField(
            model_name='winners',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Season'),
        ),
        migrations.AddField(
            model_name='rs_clubs',
            name='s_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Season'),
        ),
        migrations.AddField(
            model_name='rs_clubs',
            name='t_abr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Team'),
        ),
        migrations.AddField(
            model_name='psmatch',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Series'),
        ),
        migrations.AddField(
            model_name='postseason',
            name='participates',
            field=models.ManyToManyField(through='h_leagues.Participation', to='h_leagues.Series'),
        ),
        migrations.AddField(
            model_name='postseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Season'),
        ),
        migrations.AddField(
            model_name='postseason',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Team'),
        ),
        migrations.AddField(
            model_name='participation',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Series'),
        ),
        migrations.AddField(
            model_name='participation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.PostSeason'),
        ),
        migrations.AddField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.League'),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('league', 'season', 'phase', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='rs_clubs',
            unique_together={('t_abr', 's_year')},
        ),
        migrations.AlterUniqueTogether(
            name='postseason',
            unique_together={('team', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('team', 'series')},
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('conf', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('league', 'region')},
        ),
    ]
