# Generated by Django 2.0.2 on 2018-04-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0010_auto_20180427_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('loss', models.IntegerField(default=0)),
                ('end_point', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('h_wins', models.IntegerField(default=1)),
                ('l_wins', models.IntegerField(default=1)),
                ('conf', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=20)),
                ('high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='higher', to='h_leagues.PostSeason')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.League')),
                ('low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower', to='h_leagues.PostSeason')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Season')),
            ],
        ),
        migrations.AddField(
            model_name='postseason',
            name='participates',
            field=models.ManyToManyField(through='h_leagues.Series', to='h_leagues.PostSeason'),
        ),
        migrations.AddField(
            model_name='postseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Season'),
        ),
        migrations.AddField(
            model_name='postseason',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('league', 'season', 'phase', 'high', 'low')},
        ),
        migrations.AlterUniqueTogether(
            name='postseason',
            unique_together={('team', 'season')},
        ),
    ]
