# Generated by Django 2.0.2 on 2018-05-05 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0011_auto_20180427_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField(default=1)),
                ('h_score', models.IntegerField(default=0)),
                ('a_score', models.IntegerField(default=0)),
                ('result', models.CharField(default='', max_length=15)),
                ('storyline', models.CharField(default='', max_length=40)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h_leagues.Series')),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(choices=[('OHL', 'Ontario Hockey League'), ('QMJHL', 'Quebec Major Junior Hockey League'), ('WHL', 'Western Hockey League'), ('MMC', 'Memorial Cup')], max_length=5, primary_key=True, serialize=False),
        ),
    ]
