# Generated by Django 2.0.2 on 2018-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0012_auto_20180505_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psmatch',
            old_name='season',
            new_name='series',
        ),
        migrations.AddField(
            model_name='team',
            name='l_championship',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='mmc_championship',
            field=models.IntegerField(default=0),
        ),
    ]
