# Generated by Django 2.0.2 on 2018-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h_leagues', '0013_auto_20180506_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='winners',
            name='host',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='rs_clubs',
            name='po_marks',
            field=models.IntegerField(choices=[(1, 'w - '), (2, 'x - '), (3, 'y - '), (4, 'z - '), (0, '')], default=0),
        ),
    ]
